# Generated by Django 4.0.1 on 2022-01-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinas',
            options={'ordering': ['Medicamento'], 'verbose_name': 'Medicina', 'verbose_name_plural': 'Medicinas'},
        ),
    ]
