# Generated by Django 4.0.1 on 2022-01-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_medicinas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinas',
            name='Registro',
            field=models.BooleanField(default=True, verbose_name='Registro'),
        ),
    ]
