# Generated by Django 4.0.1 on 2022-01-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('Password', models.CharField(max_length=55, verbose_name='Contraseña')),
                ('Email', models.EmailField(max_length=100, verbose_name='Correo')),
                ('Fecha_Nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Ultimo_Inicio', models.DateTimeField(auto_now=True, verbose_name='Ultimo inicio')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
