# Generated by Django 4.0.1 on 2022-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Password',
            field=models.CharField(max_length=110, verbose_name='Contraseña'),
        ),
    ]
