# Generated by Django 4.0.1 on 2022-01-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_usuario_id_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=70, verbose_name='Nombre'),
        ),
    ]
