# Generated by Django 4.0.1 on 2022-01-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_alter_usuario_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ID_Paciente',
        ),
    ]
