# Generated by Django 4.0.1 on 2022-01-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_usuario_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Paciente',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Paciente',
            field=models.ManyToManyField(blank=True, null=True, to='Usuarios.Usuario'),
        ),
    ]
