# Generated by Django 4.0.1 on 2022-01-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_alter_usuario_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Paciente',
        ),
        migrations.CreateModel(
            name='rel_Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aceptado', models.BooleanField(verbose_name='Aceptado')),
                ('Cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Cuidador', to='Usuarios.usuario')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Paciente', to='Usuarios.usuario')),
            ],
        ),
    ]
