# Generated by Django 4.0.1 on 2022-01-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['Num_Dia', 'Hora', 'Minutos'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='Dia',
            new_name='Num_Dia',
        ),
    ]
