# Generated by Django 4.0.1 on 2022-01-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0003_alter_horario_hora_alter_horario_minutos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='Minutos',
            field=models.IntegerField(blank=True, default=0, verbose_name='Minutos'),
        ),
    ]
