# Generated by Django 4.0.1 on 2022-01-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0004_alter_horario_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='Hora',
            field=models.IntegerField(blank=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='Minutos',
            field=models.IntegerField(blank=True, verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='Num_Dia',
            field=models.IntegerField(blank=True, verbose_name='Dia de la semana'),
        ),
    ]
