# Generated by Django 4.0.1 on 2022-01-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0006_rename_horario_set_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set_horario',
            options={'ordering': ['Hora', 'Minutos', 'Medicamento'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
    ]
