# Generated by Django 4.0.1 on 2022-01-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0002_alter_usuario_password'),
        ('Inventario', '0002_alter_medicinas_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Hora', models.DateTimeField(auto_now_add=True, verbose_name='Hora')),
                ('Dosis', models.FloatField(verbose_name='Dosis')),
                ('ID_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.medicinas')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
